"""Generate spell.effecoria.<id>.desc entries for en_us.json and ru_ru.json from spell JSON."""
from __future__ import annotations

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
SPELLS = ROOT / "src/main/resources/data/effecoria/spells"
EN = ROOT / "src/main/resources/assets/effecoria/lang/en_us.json"
RU = ROOT / "src/main/resources/assets/effecoria/lang/ru_ru.json"

EFFECT_EN = {
    "fireball": "Hurls a flaming orb that ignites targets and ground.",
    "great_fireball": "Massive fire orb that sheds flame and scorches a wide patch on impact.",
    "plasma_bolt": "Fires a superheated plasma bolt that burns hard.",
    "water_stream": "Lashes a pressurized water stream along your look.",
    "hydro_slice": "High-pressure cutter that shreds soft targets and foliage.",
    "steam_jet": "Scalding steam cone that leaves lingering fog.",
    "ice_shard": "Launches a piercing ice shard that slows hits.",
    "ice_sheet": "Freezes the ground into a slick sheet.",
    "ice_prison": "Encases the target in a temporary ice shell.",
    "wind_push": "Blasts wind that knocks foes back.",
    "air_hand": "Grabs a target with a wind-formed hand; cast again to release.",
    "air_ionization": "Charges the air with crackling ions.",
    "shockwave": "Radial kinetic burst around you.",
    "sonic_lance": "Focused sonic spear along your aim.",
    "tornado": "Spins up a short-lived tornado field.",
    "lightning_spear": "Calls a lightning spear onto the aim point.",
    "vacuum_cage": "Imprisons foes in a crushing vacuum.",
    "water_prison": "Roots a target inside a water shell.",
    "steam_flight": "Steam-powered flight; drains Ψ while active.",
    "steam_veil": "Cloaks you in concealing steam.",
    "breath_bubble": "Breathable bubble for underwater work.",
    "water_shield": "Water barrier that softens incoming hits.",
    "water_shroud": "Elemental water shroud around the caster.",
    "air_shroud": "Elemental air shroud around the caster.",
    "air_form": "Shift briefly into a light air form.",
    "ember_volley": "Sprays several embers forward.",
    "mirage": "Heat shimmer that confuses perception.",
    "ion_storm": "Localized ion storm around you.",
    "hyper_cooling": "Flash-freezes the area ahead.",
    "frost_bastion": "Raises a frost barrier.",
    "cryo_wave": "Sends a freezing wave outward.",
    "atmospheric_pressure": "Crushes with sudden air pressure.",
    "hurricane_storm": "Wide storm of wind and debris.",
    "plasma_barrage": "Rapid plasma shots.",
    "thermonuclear_pulse": "Devastating heat pulse.",
    "absolute_zero": "Extreme cold that nearly stops motion.",
    "meteorological_cataclysm": "Unleashes a catastrophic weather surge.",
    "quasar": "Blinding high-energy beam.",
    "elemental_supremacy": "Brief mastery surge of elemental forces.",
    "weak_breeze": "Gentle starter breeze for practice casts.",
    "telekinesis": "Shoves the target along your look.",
    "mind_sting": "Mental sting that damages and slows.",
    "mind_bolt": "Psychic bolt at a living target.",
    "sense_phi": "Reveals Φ density and nearby signatures.",
    "psychic_barrier": "Mental shield against harm.",
    "psychic_amplify": "Amplifies your next psychic output.",
    "neural_lock": "Locks the target's nerves briefly.",
    "mind_lance": "Piercing psychic lance.",
    "thought_lance": "Long-range thought spear.",
    "telekinetic_crush": "Crushes the target with telekinetic force.",
    "psychic_scream": "AoE psychic scream around you.",
    "mind_probe": "Reads surface intent from a target.",
    "mass_confusion": "Confuses nearby minds.",
    "synaptic_overload": "Overloads the target's synapses.",
    "psychic_drain": "Drains mental stamina into yourself.",
    "psychic_focus": "Steadies concentration for cheaper casts.",
    "psychic_storm": "Wide psychic storm field.",
    "mental_fortress": "Hardens your mind against disruption.",
    "thought_bomb": "Detonates a delayed psychic charge on a target.",
    "omega_mind": "Ultimate mental overload.",
    "mental_push": "Starter telekinetic shove.",
    "mental_sting": "Starter psychic sting.",
    "diagnostic_glimpse": "Reads vital signs of a target.",
    "life_sense": "Senses living signatures nearby.",
    "vitality_pulse": "Pulses healing vitality through you.",
    "blood_stasis": "Temporarily stills bleeding and flow.",
    "bio_strike": "Organic strike that bruises tissue.",
    "bone_needle": "Fires a bone needle projectile.",
    "foreign_agent": "Seeds a hostile agent in the target.",
    "muscle_spasm": "Forces painful muscle spasms.",
    "thorn_lash": "Lashes with living thorns.",
    "root_bind": "Roots the target in place.",
    "chitin_plates": "Grows temporary chitin armor.",
    "acid_gland": "Sprays corrosive acid.",
    "bone_spur": "Erupts bone spurs around you.",
    "sense_sharpening": "Sharpens senses briefly.",
    "pain_inhibitor": "Dulls pain and shock.",
    "poison_thorns": "Poisoned thorn burst.",
    "bio_mimicry": "Mimics a safer metabolic state.",
    "organism_adaptation": "Adapts your body to the environment.",
    "metabolic_shock": "Shocks the target's metabolism.",
    "parasitic_infection": "Inflicts a parasitic infection.",
    "immune_suppression": "Weakens the target's defenses.",
    "metabolic_boost": "Boosts your metabolism and regen.",
    "organic_necrosis": "Forces necrotic collapse in tissue.",
    "briar_surge": "Surges briars through the ground.",
    "verdant_mend": "Mends wounds with verdant growth.",
    "symbiotic_graft": "Grafts a symbiotic buff onto a target.",
    "full_restructuring": "Deeply restructures your body.",
    "biological_field": "Projects a biological field.",
    "verdant_bloom": "Blooms healing flora nearby.",
    "scorched_earth": "Burns organic matter in a patch.",
    "bio_fission": "Splits biomass explosively.",
    "super_regeneration": "Rapid regeneration burst.",
    "limb_regeneration": "Regrows damaged limbs over time.",
    "population_control": "Culls weak organisms in radius.",
    "genetic_lock": "Locks the target's genetics briefly.",
    "biological_plague": "Spreads a biological plague.",
    "biological_cleaving": "Cleaves living tissue hard.",
    "living_armor": "Living armor plates.",
    "beast_form": "Partial beast transformation.",
    "full_transformation": "Full beast transformation.",
    "spore_storm": "Storm of infectious spores.",
    "bio_cataclysm": "Catastrophic bio-surge.",
    "absolute_regeneration": "Near-total regenerative surge.",
    "cellular_dominion": "Dominates nearby cellular matter.",
    "biological_singularity": "Collapses life into a singularity.",
    "life_creation": "Attempts to spark new life.",
    "biological_immortality": "Brief brush with immortality.",
    "evolutionary_leap": "Forces a sudden evolutionary leap.",
    "shade_summon": "Calls a permanent shade thrall (reserves Ψ while it lives).",
    "shade_brood": "Calls several permanent shade thralls (each reserves Ψ).",
    "shade_swarm": "Swarms permanent shades around you (each reserves Ψ).",
    "raise_skeleton": "Raises a permanent skeleton thrall (reserves Ψ while it lives).",
    "raise_zombie": "Raises a permanent zombie thrall (reserves Ψ while it lives).",
    "army_of_dead": "Raises several permanent skeleton thralls (each reserves Ψ).",
    "death_sense": "Senses wounded life nearby.",
    "bone_chill": "Chills bones with necrotic cold.",
    "necrotic_bolt": "Fires a necrotic bolt.",
    "soul_drain": "Drains life from a target into you.",
    "wither_touch": "Withering touch on contact.",
    "grave_whisper": "Whispers of the grave unsettle a target.",
    "curse_of_frailty": "Curses the target with frailty.",
    "siphon_pulse": "Pulses siphoned life energy.",
    "bone_armor": "Raises bone armor plates.",
    "phantom_step": "Steps briefly as a phantom.",
    "grave_bind": "Binds the target with grave weight.",
    "life_tap": "Damages a target and heals you for part of it.",
    "haunting_visage": "Haunts the target's vision.",
    "soul_shackle": "Shackles the target's soul briefly.",
    "bone_volley": "Volley of bone shards.",
    "wither_wave": "Wave of wither around you.",
    "necrotic_aura": "Aura of necrosis.",
    "dark_pact": "Pact: power now, weakness after.",
    "grave_leech": "Leeches life through the grave.",
    "corpse_burst": "Bursts necrotic energy from a target.",
    "grave_field": "Spreads a grave field.",
    "soul_anchor": "Anchors a soul to resist displacement.",
    "death_coil": "Coil of death energy at a target.",
    "soul_reaper": "Reaps soul essence from a target.",
    "lich_ward": "Ward that hardens you against death.",
    "death_gate": "Short death-aspected blink with a damaging trail.",
    "phylactery_surge": "Surges phylactery energy (placeholder).",
    "soul_cataclysm": "Cataclysmic soul eruption.",
    "death_apotheosis": "Peak necromantic apotheosis.",
    "lich_ascension": "Locked until phylactery / mage tower content.",
    "blink": "Short-range teleport along your look.",
    "far_blink": "Long-range blink with a spatial trail.",
    "warp_bolt": "Warping bolt that strikes a target.",
    "phase_veil": "Phases you briefly out of harm.",
    "spatial_ward": "Spatial ward against displacement.",
    "rift_yank": "Yanks a target through a rift to you.",
    "fold_repulse": "Folds space to repulse a target.",
    "rift_slash": "Slashes with a spatial rift.",
    "gravity_snare": "Snares foes with gravity.",
    "void_step": "Steps through void space.",
    "dimensional_anchor": "Anchors a target against teleport.",
    "gravity_well": "Creates a gravity well.",
    "warp_exchange": "Swaps places with a target.",
    "spatial_surge": "Surges spatial force outward.",
    "void_lance": "Lance of void energy.",
    "rift_burst": "Burst from a closing rift.",
    "spatial_singularity": "Forms a short singularity.",
    "absolute_fold": "Folds space absolutely around you.",
    "corrupt_mark": "Marks a target with corruption.",
    "blight_pulse": "Pulse of blight around you.",
    "rot_touch": "Rotting touch on a target.",
    "entropy_lash": "Lash of entropy.",
    "binding_seal": "Combat binding seal on a target.",
    "plague_bolt": "Bolt of plague.",
    "festering_wound": "Opens a festering wound.",
    "miasma_cloak": "Cloak of miasma.",
    "blight_brand": "Brands with blight.",
    "blight_surge": "Surges blight outward.",
    "decay_bind": "Binds with decay.",
    "pestilence_wave": "Wave of pestilence.",
    "blight_field": "Field of lingering blight.",
    "entropy_aegis": "Aegis woven from entropy.",
    "tainted_leech": "Leeches with tainted energy.",
    "virulent_wave": "Virulent infection wave.",
    "plague_crown": "Crowns you with plague aura.",
    "omega_blight": "Ultimate blight eruption.",
    "place_trap_seal": "Inscribes a damage trap seal on a block.",
    "place_glow_seal": "Inscribes a glow seal on a block.",
    "place_fortify_seal": "Inscribes a fortify seal on a block.",
    "place_snare_seal": "Inscribes a snare seal on a block.",
    "place_repulse_seal": "Inscribes a repulse seal on a block.",
}

EFFECT_RU = {
    "fireball": "Метает огненный шар, поджигающий цель и землю.",
    "great_fireball": "Огромный огненный шар, осыпающий пламя и выжигающий зону при ударе.",
    "plasma_bolt": "Выстрел перегретой плазмой с сильным ожогом.",
    "water_stream": "Удар струёй воды вдоль взгляда.",
    "hydro_slice": "Режущая струя высокого давления.",
    "steam_jet": "Обжигающий конус пара с остаточным туманом.",
    "ice_shard": "Ледяной осколок, замедляющий цель.",
    "ice_sheet": "Замораживает землю в скользкий слой.",
    "ice_prison": "Заковывает цель во временную ледяную оболочку.",
    "wind_push": "Порыв ветра, отбрасывающий врагов.",
    "air_hand": "Хватает цель воздушной рукой; повторный каст отпускает.",
    "air_ionization": "Заряжает воздух ионами.",
    "shockwave": "Радиальный кинетический удар вокруг вас.",
    "sonic_lance": "Звуковое копьё по прицелу.",
    "tornado": "Кратковременный смерч.",
    "lightning_spear": "Призывает молниеносное копьё.",
    "vacuum_cage": "Ловит врагов в вакуумную клетку.",
    "water_prison": "Заключает цель в водную оболочку.",
    "steam_flight": "Паровой полёт; пока активен — тратит Ψ.",
    "steam_veil": "Маскирующая паровая пелена.",
    "breath_bubble": "Пузырь воздуха для дыхания под водой.",
    "water_shield": "Водный щит, смягчающий удары.",
    "water_shroud": "Водный покров вокруг заклинателя.",
    "air_shroud": "Воздушный покров вокруг заклинателя.",
    "air_form": "Кратко принимает лёгкую воздушную форму.",
    "ember_volley": "Веер раскалённых угольков.",
    "mirage": "Марево, путающее восприятие.",
    "ion_storm": "Локальный ионный шторм.",
    "hyper_cooling": "Мгновенно вымораживает зону впереди.",
    "frost_bastion": "Поднимает ледяной бастион.",
    "cryo_wave": "Волна холода вокруг.",
    "atmospheric_pressure": "Давит внезапным давлением воздуха.",
    "hurricane_storm": "Широкий ураган обломков и ветра.",
    "plasma_barrage": "Очередь плазменных выстрелов.",
    "thermonuclear_pulse": "Опустошающий тепловой импульс.",
    "absolute_zero": "Экстремальный холод, почти останавливающий движение.",
    "meteorological_cataclysm": "Катастрофический погодный всплеск.",
    "quasar": "Ослепляющий луч высокой энергии.",
    "elemental_supremacy": "Краткий всплеск власти стихий.",
    "weak_breeze": "Слабый учебный ветерок.",
    "telekinesis": "Толкает цель вдоль взгляда.",
    "mind_sting": "Ментальный укол с уроном и замедлением.",
    "mind_bolt": "Пси-заряд по живой цели.",
    "sense_phi": "Показывает плотность Φ и сигнатуры рядом.",
    "psychic_barrier": "Ментальный щит.",
    "psychic_amplify": "Усиливает следующий психический выброс.",
    "neural_lock": "Кратко блокирует нервы цели.",
    "mind_lance": "Пронзающее пси-копьё.",
    "thought_lance": "Дальняя мысленная пика.",
    "telekinetic_crush": "Сжимает цель телекинезом.",
    "psychic_scream": "Пси-крик вокруг вас.",
    "mind_probe": "Считывает поверхностные намерения цели.",
    "mass_confusion": "Запутывает ближайшие умы.",
    "synaptic_overload": "Перегружает синапсы цели.",
    "psychic_drain": "Вытягивает ментальную силу в вас.",
    "psychic_focus": "Стабилизирует концентрацию.",
    "psychic_storm": "Широкий пси-шторм.",
    "mental_fortress": "Укрепляет разум.",
    "thought_bomb": "Отложенный пси-заряд на цели.",
    "omega_mind": "Предельная ментальная перегрузка.",
    "mental_push": "Стартовый телекинетический толчок.",
    "mental_sting": "Стартовый пси-укол.",
    "diagnostic_glimpse": "Считывает жизненные показатели цели.",
    "life_sense": "Чувствует живые сигнатуры рядом.",
    "vitality_pulse": "Пульс исцеляющей жизненности.",
    "blood_stasis": "Временно останавливает кровоток.",
    "bio_strike": "Органический удар по тканям.",
    "bone_needle": "Костная игла-снаряд.",
    "foreign_agent": "Вживляет враждебный агент в цель.",
    "muscle_spasm": "Вызывает болезненные спазмы.",
    "thorn_lash": "Удар живыми шипами.",
    "root_bind": "Укореняет цель на месте.",
    "chitin_plates": "Временная хитиновая броня.",
    "acid_gland": "Выброс едкой кислоты.",
    "bone_spur": "Костные шипы вокруг вас.",
    "sense_sharpening": "Кратко обостряет чувства.",
    "pain_inhibitor": "Приглушает боль и шок.",
    "poison_thorns": "Ядовитый шиповый выброс.",
    "bio_mimicry": "Мимикрия более безопасного состояния.",
    "organism_adaptation": "Адаптирует тело к среде.",
    "metabolic_shock": "Шок метаболизма цели.",
    "parasitic_infection": "Паразитарная инфекция.",
    "immune_suppression": "Ослабляет защиту цели.",
    "metabolic_boost": "Ускоряет метаболизм и реген.",
    "organic_necrosis": "Некроз тканей цели.",
    "briar_surge": "Волна терновника из земли.",
    "verdant_mend": "Лечит зелёным ростом.",
    "symbiotic_graft": "Симбиотический эффект на цели.",
    "full_restructuring": "Глубокая перестройка тела.",
    "biological_field": "Биологическое поле вокруг.",
    "verdant_bloom": "Цветение исцеляющей флоры.",
    "scorched_earth": "Выжигает органику на участке.",
    "bio_fission": "Взрывное деление биомассы.",
    "super_regeneration": "Всплеск быстрой регенерации.",
    "limb_regeneration": "Регенерация конечностей со временем.",
    "population_control": "Прореживает слабые организмы.",
    "genetic_lock": "Кратко блокирует генетику цели.",
    "biological_plague": "Распространяет биологическую чуму.",
    "biological_cleaving": "Жёсткий разрез живой ткани.",
    "living_armor": "Живая броня.",
    "beast_form": "Частичное превращение в зверя.",
    "full_transformation": "Полное звериное превращение.",
    "spore_storm": "Шторм заразных спор.",
    "bio_cataclysm": "Катастрофический био-всплеск.",
    "absolute_regeneration": "Почти полная регенерация.",
    "cellular_dominion": "Власть над клеточной материей рядом.",
    "biological_singularity": "Схлопывает жизнь в сингулярность.",
    "life_creation": "Пытается зажечь новую жизнь.",
    "biological_immortality": "Краткое касание бессмертия.",
    "evolutionary_leap": "Вынужденный эволюционный скачок.",
    "shade_summon": "Призывает вечную тень-слугу (резервирует Ψ, пока жива).",
    "shade_brood": "Несколько вечных теней (каждая резервирует Ψ).",
    "shade_swarm": "Рой вечных теней (каждая резервирует Ψ).",
    "raise_skeleton": "Вечный скелет-слуга (резервирует Ψ, пока жив).",
    "raise_zombie": "Вечный зомби-слуга (резервирует Ψ, пока жив).",
    "army_of_dead": "Несколько вечных скелетов (каждый резервирует Ψ).",
    "death_sense": "Чувствует раненых рядом.",
    "bone_chill": "Некротический холод в костях.",
    "necrotic_bolt": "Некротический заряд.",
    "soul_drain": "Вытягивает жизнь цели в вас.",
    "wither_touch": "Иссушающее касание.",
    "grave_whisper": "Шёпот могилы тревожит цель.",
    "curse_of_frailty": "Проклятие хрупкости.",
    "siphon_pulse": "Пульс вытянутой жизненной силы.",
    "bone_armor": "Костная броня.",
    "phantom_step": "Шаг призрака.",
    "grave_bind": "Связывает цель могильной тяжестью.",
    "life_tap": "Бьёт цель и лечит вас частью урона.",
    "haunting_visage": "Преследует зрение цели.",
    "soul_shackle": "Кратко сковывает душу цели.",
    "bone_volley": "Залп костных осколков.",
    "wither_wave": "Волна иссушения вокруг.",
    "necrotic_aura": "Аура некроза.",
    "dark_pact": "Пакт: сила сейчас, слабость потом.",
    "grave_leech": "Пиявка через могилу.",
    "corpse_burst": "Взрыв некротической энергии в цели.",
    "grave_field": "Поле могильной порчи.",
    "soul_anchor": "Якорит душу против смещения.",
    "death_coil": "Змея смертельной энергии в цель.",
    "soul_reaper": "Жнёт душевную суть цели.",
    "lich_ward": "Защита от смерти.",
    "death_gate": "Короткий прыжок смерти со следом урона.",
    "phylactery_surge": "Всплеск филактерии (заготовка).",
    "soul_cataclysm": "Катаклизм душ.",
    "death_apotheosis": "Вершина некромантии.",
    "lich_ascension": "Закрыто до филактерии / башни мага.",
    "blink": "Короткий телепорт вдоль взгляда.",
    "far_blink": "Дальний блинк со следом.",
    "warp_bolt": "Искажающий заряд по цели.",
    "phase_veil": "Кратко фазирует вас из-под удара.",
    "spatial_ward": "Пространственная защита.",
    "rift_yank": "Рвёт цель к вам через разлом.",
    "fold_repulse": "Складывает пространство и отталкивает цель.",
    "rift_slash": "Удар пространственным разломом.",
    "gravity_snare": "Ловушка гравитации.",
    "void_step": "Шаг через пустоту.",
    "dimensional_anchor": "Якорит цель против телепорта.",
    "gravity_well": "Гравитационный колодец.",
    "warp_exchange": "Меняет вас местами с целью.",
    "spatial_surge": "Всплеск пространственной силы.",
    "void_lance": "Копьё пустоты.",
    "rift_burst": "Взрыв закрывающегося разлома.",
    "spatial_singularity": "Краткая сингулярность.",
    "absolute_fold": "Абсолютно складывает пространство вокруг.",
    "corrupt_mark": "Метка порчи на цели.",
    "blight_pulse": "Пульс порчи вокруг.",
    "rot_touch": "Гнилое касание.",
    "entropy_lash": "Плеть энтропии.",
    "binding_seal": "Боевая связывающая печать на цели.",
    "plague_bolt": "Заряд чумы.",
    "festering_wound": "Вскрывает гноящуюся рану.",
    "miasma_cloak": "Плащ миазмов.",
    "blight_brand": "Клеймо порчи.",
    "blight_surge": "Всплеск порчи.",
    "decay_bind": "Связь распада.",
    "pestilence_wave": "Волна мора.",
    "blight_field": "Поле тлеющей порчи.",
    "entropy_aegis": "Эгида из энтропии.",
    "tainted_leech": "Пиявка порченой энергии.",
    "virulent_wave": "Волна вирулентной инфекции.",
    "plague_crown": "Корона чумной ауры.",
    "omega_blight": "Предельный выброс порчи.",
    "place_trap_seal": "Наносит на блок печать-ловушку.",
    "place_glow_seal": "Наносит на блок печать свечения.",
    "place_fortify_seal": "Наносит на блок печать укрепления.",
    "place_snare_seal": "Наносит на блок печать силка.",
    "place_repulse_seal": "Наносит на блок печать отталкивания.",
}

SCHOOL_FALLBACK_EN = {
    "elemental": "Elemental working shaped by fire, water, air, or ice.",
    "mental": "Psychic working that bends mind and motion.",
    "organic": "Organic working over flesh, growth, and adaptation.",
    "necromancy": "Necromantic working of bone, shade, and soul.",
    "spatial": "Spatial working that folds distance and gravity.",
    "corruption": "Corruptive working of blight, rot, and entropy.",
    "seals": "Inscribes a lasting seal on a block.",
}

SCHOOL_FALLBACK_RU = {
    "elemental": "Стихийное воздействие огнём, водой, воздухом или льдом.",
    "mental": "Психическое воздействие на разум и движение.",
    "organic": "Органическое воздействие на плоть, рост и адаптацию.",
    "necromancy": "Некромантия костей, теней и душ.",
    "spatial": "Пространственное складывание дистанции и гравитации.",
    "corruption": "Порча: гниль, мор и энтропия.",
    "seals": "Наносит на блок постоянную печать.",
}

SEAL_SPELL_TYPES = {
    "trap_seal": "place_trap_seal",
    "glow_seal": "place_glow_seal",
    "fortify_seal": "place_fortify_seal",
    "snare_glyph": "place_snare_seal",
    "repulsion_seal": "place_repulse_seal",
    "beacon_seal": "place_glow_seal",
    "shock_glyph": "place_trap_seal",
    "ward_glyph": "place_fortify_seal",
    "anchor_fortify": "place_fortify_seal",
    "permanent_glow": "place_glow_seal",
    "snare_matrix": "place_snare_seal",
    "shock_trap": "place_trap_seal",
    "omega_ward": "place_fortify_seal",
}


def effect_path(effect: dict) -> str:
    t = effect.get("type", "")
    if isinstance(t, str) and ":" in t:
        return t.split(":", 1)[1]
    return str(t)


def describe(spell_id: str, school: str, effects: list[dict], table: dict, fallback: dict) -> str:
    if not effects:
        return fallback.get(school, "An Effecoria spell.")
    # Prefer first known effect description; join unique if multiple.
    parts = []
    seen = set()
    for eff in effects:
        path = effect_path(eff)
        text = table.get(path)
        if text and text not in seen:
            parts.append(text)
            seen.add(text)
    if not parts:
        # seal spell ids without matching effect map
        mapped = SEAL_SPELL_TYPES.get(spell_id)
        if mapped and mapped in table:
            return table[mapped]
        return fallback.get(school, "An Effecoria spell.")
    return " ".join(parts[:2])


def main() -> None:
    en = json.loads(EN.read_text(encoding="utf-8"))
    ru = json.loads(RU.read_text(encoding="utf-8"))
    added = 0
    for path in sorted(SPELLS.rglob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        sid = data["id"].split(":")[-1]
        school = data.get("school") or path.parent.name
        effects = data.get("effects") or []
        en_key = f"spell.effecoria.{sid}.desc"
        ru_key = f"spell.effecoria.{sid}.desc"
        en[en_key] = describe(sid, school, effects, EFFECT_EN, SCHOOL_FALLBACK_EN)
        ru[ru_key] = describe(sid, school, effects, EFFECT_RU, SCHOOL_FALLBACK_RU)
        added += 1

    en["gui.effecoria.hub.summon_reserve"] = "Thrall reserves %s Ψ while alive (not spent on cast)"
    ru["gui.effecoria.hub.summon_reserve"] = "Слуга резервирует %s Ψ, пока жив (не тратится при касте)"

    EN.write_text(json.dumps(en, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    RU.write_text(json.dumps(ru, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote descriptions for {added} spells + summon reserve hub hint.")


if __name__ == "__main__":
    main()
